### ISSUE TITLE
Jimmie NGAP onboarding

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/cloud-tasks#41]

**Comment by jimmie** [comment]
Looking at NAMS it appears my original request was cancelled by the system due to no response from the sponsor. I have resubmitted the request, submitted another for Skillsoft access to two of the required training exercises and emailed Jason Werpy to alert him of the invalidated request.

I have completed the Elevated Privileges course.

**Comment by jimmie** [comment]
Skillsoft training has been completed, NGAP NAMS request has been approved and awaiting provisioning.
